### ISSUE TITLE
Meeting: Zwischenbesprechung am 14.01.22 ??

### ISSUE THREAD

**Issue by dwori** [domiK66/SportChimp#40]
@Frolic97 @mensiq @Giu52 @domiK66 @dwori 
Kurz besprechen damit alle am gleichen Stand sind.

- Was noch an Funktionen eingebaut werden muss
- Was noch "gestyled" werden muss
- Wo noch bugs sind
- Security
- Documentation / Installation guide updaten

**Comment by Frolic97** [comment]
Geht klar :)

**Comment by dwori** [comment]
10:00 passt?
